# Generated by Django 4.2.7 on 2026-05-13 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AwesomePackages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "starRating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        default=5,
                    ),
                ),
                ("days", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("persons", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("East Africa Tours", "EA-T"),
                            ("Africa Tours", "A-T"),
                            ("International Tours", "I-T"),
                        ],
                        default="East Africa Tours",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="awesome_packages/default.jpg",
                        upload_to="awesome_packages/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DestinationsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="destinations_category/"
                    ),
                ),
                (
                    "image_orientation",
                    models.CharField(
                        choices=[("landscape", "Landscape"), ("portrait", "Portrait")],
                        default="landscape",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MustVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="must_visit_images/")),
                (
                    "size",
                    models.CharField(
                        choices=[("landscape", "Landscape"), ("portrait", "Portrait")],
                        default="landscape",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackagePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("number_of_persons", models.IntegerField()),
                ("travel_date", models.DateField()),
                ("special_requests", models.TextField(blank=True)),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "amount_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="Places.awesomepackages",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Destinations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="destinations/"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Places.destinationscategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "activities",
                    models.TextField(
                        blank=True,
                        help_text="List activities for this day, separated by commas",
                    ),
                ),
                ("accommodation", models.CharField(blank=True, max_length=200)),
                (
                    "meals",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast Only"),
                            ("Half Board", "Breakfast & Dinner"),
                            ("Full Board", "Breakfast, Lunch & Dinner"),
                            ("All Inclusive", "All Meals & Drinks"),
                        ],
                        default="Full Board",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="itinerary_images/"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to="Places.awesomepackages",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
                "unique_together": {("package", "day_number")},
            },
        ),
    ]
