# Generated by Django 4.2.7 on 2026-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awesomepackages",
            name="category",
            field=models.CharField(
                choices=[
                    ("East Africa Tours", "EA-T"),
                    ("South Africa", "S-A"),
                    ("West Africa", "W-A"),
                    ("Africa Tours", "A-T"),
                    ("International Tours", "I-T"),
                    ("Cruises", "cruises"),
                ],
                default="East Africa Tours",
                max_length=50,
            ),
        ),
    ]
