# Generated by Django 4.2.7 on 2026-06-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Places", "0002_alter_awesomepackages_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncluisiveExcluisive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Places.awesomepackages",
                    ),
                ),
            ],
        ),
    ]
