# Generated by Django 4.2.7 on 2026-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Places", "0003_incluisiveexcluisive"),
    ]

    operations = [
        migrations.AddField(
            model_name="incluisiveexcluisive",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
