# Generated by Django 4.2.7 on 2026-07-16 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Places", "0008_populate_awesomepackages_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awesomepackages",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
            },
        ),
        migrations.AlterModelOptions(
            name="destinations",
            options={
                "ordering": ["name"],
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
            },
        ),
        migrations.AlterModelOptions(
            name="destinationscategory",
            options={
                "ordering": ["category"],
                "verbose_name": "Destination Category",
                "verbose_name_plural": "Destination Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="incluisiveexcluisive",
            options={
                "ordering": ["-is_inclusive", "name"],
                "verbose_name": "Inclusion/Exclusion",
                "verbose_name_plural": "Inclusions/Exclusions",
            },
        ),
        migrations.AlterModelOptions(
            name="mustvisit",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="packagepurchase",
            options={
                "ordering": ["-purchase_date"],
                "verbose_name": "Package Purchase",
                "verbose_name_plural": "Package Purchases",
            },
        ),
        migrations.RenameField(
            model_name="awesomepackages",
            old_name="starRating",
            new_name="star_rating",
        ),
        migrations.RenameField(
            model_name="incluisiveexcluisive",
            old_name="status",
            new_name="is_inclusive",
        ),
        migrations.AddField(
            model_name="awesomepackages",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destinations",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mustvisit",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="awesomepackages",
            name="category",
            field=models.CharField(
                choices=[
                    ("East Africa Tours", "EA-T"),
                    ("South Africa", "S-A"),
                    ("West Africa", "W-A"),
                    ("Africa Tours", "A-T"),
                    ("International Tours", "I-T"),
                    ("Cruises", "cruises"),
                ],
                db_index=True,
                default="East Africa Tours",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="awesomepackages",
            name="location",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="awesomepackages",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="awesomepackages",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="destinations",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinations",
                to="Places.destinationscategory",
            ),
        ),
        migrations.AlterField(
            model_name="destinations",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="destinations",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="destinationscategory",
            name="category",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="destinationscategory",
            name="location",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="incluisiveexcluisive",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inclusions",
                to="Places.awesomepackages",
            ),
        ),
        migrations.AlterField(
            model_name="packagepurchase",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="packagepurchase",
            name="full_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="packagepurchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="packagepurchase",
            name="travel_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="awesomepackages",
            index=models.Index(fields=["name"], name="Places_awes_name_a43102_idx"),
        ),
        migrations.AddIndex(
            model_name="awesomepackages",
            index=models.Index(
                fields=["category"], name="Places_awes_categor_d0749e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="awesomepackages",
            index=models.Index(fields=["price"], name="Places_awes_price_7399c8_idx"),
        ),
        migrations.AddIndex(
            model_name="awesomepackages",
            index=models.Index(fields=["slug"], name="Places_awes_slug_c54934_idx"),
        ),
        migrations.AddIndex(
            model_name="awesomepackages",
            index=models.Index(
                fields=["category", "price"], name="Places_awes_categor_5b1a2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="destinations",
            index=models.Index(fields=["name"], name="Places_dest_name_022a98_idx"),
        ),
        migrations.AddIndex(
            model_name="destinations",
            index=models.Index(
                fields=["category", "name"], name="Places_dest_categor_699837_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="destinations",
            index=models.Index(fields=["price"], name="Places_dest_price_e6847d_idx"),
        ),
        migrations.AddIndex(
            model_name="destinationscategory",
            index=models.Index(
                fields=["category"], name="Places_dest_categor_ff46dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="destinationscategory",
            index=models.Index(
                fields=["location"], name="Places_dest_locatio_6faa3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerary",
            index=models.Index(
                fields=["package", "day_number"], name="Places_itin_package_afb368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagepurchase",
            index=models.Index(fields=["email"], name="Places_pack_email_544953_idx"),
        ),
        migrations.AddIndex(
            model_name="packagepurchase",
            index=models.Index(fields=["status"], name="Places_pack_status_2cc6d6_idx"),
        ),
        migrations.AddIndex(
            model_name="packagepurchase",
            index=models.Index(
                fields=["travel_date"], name="Places_pack_travel__07860d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagepurchase",
            index=models.Index(
                fields=["purchase_date"], name="Places_pack_purchas_242faa_idx"
            ),
        ),
    ]
