# Generated by Django 4.2.7 on 2026-07-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Places", "0009_alter_awesomepackages_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="destination_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as the main image for this destination",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of images in the gallery"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Places.destinations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destination Image",
                "verbose_name_plural": "Destination Images",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
