# Generated by Django 5.2.17 on 2026-10-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0010_destinationimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MustVisit',
        ),
    ]
