# Generated by Django 4.2.7 on 2026-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
