# Generated by Django 4.2.7 on 2026-07-01 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Invoices", "0002_invoice_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvolvedBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="budget",
            field=models.ManyToManyField(
                blank=True, related_name="invoices", to="Invoices.involvedbudget"
            ),
        ),
    ]
