# Generated by Django 4.2.7 on 2026-07-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Invoices", "0003_involvedbudget_invoice_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="budget",
        ),
        migrations.DeleteModel(
            name="InvolvedBudget",
        ),
    ]
