# Generated by Django 4.2.7 on 2026-05-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accomodations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="house 1", max_length=100)),
                ("location", models.CharField(default="Nairobi", max_length=100)),
                (
                    "specification",
                    models.CharField(
                        choices=[
                            ("1b", "1 Bedroom"),
                            ("2b", "2 Bedroom"),
                            ("3b", "3 Bedroom"),
                            ("4b", "4 Bedroom"),
                            ("Studio", "Studio"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("max_guests", models.IntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AirBNB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "specification",
                    models.CharField(
                        choices=[
                            ("1b", "1 Bedroom"),
                            ("2b", "2 Bedroom"),
                            ("3b", "3 Bedroom"),
                            ("4b", "4 Bedroom"),
                            ("Studio", "Studio"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("max_guests", models.IntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AirBNBImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="AirBNB/default.jpg", upload_to="AirBNB/"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "airbnb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Accomodations.airbnb",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AirBNBBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=100)),
                ("guest_email", models.EmailField(max_length=254)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("guests", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "airbnb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="Accomodations.airbnb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccomodationsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="Accomodations/default.jpg", upload_to="Accomodations/"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accomodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Accomodations.accomodations",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-uploaded_at"],
            },
        ),
    ]
