# Generated by Django 4.2.7 on 2026-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accomodations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="accomodations",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="accomodations",
            name="meal_plan",
            field=models.ManyToManyField(
                blank=True, related_name="accomodations", to="Accomodations.mealplan"
            ),
        ),
    ]
