# Generated by Django 4.2.7 on 2026-07-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accomodations", "0002_mealplan_accomodations_contact_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accomodations",
            name="child_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="accomodations",
            name="contract_validity",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accomodations",
            name="destinations",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="accomodations",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="accomodations",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="accomodations",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 Star"),
                    ("2", "2 Star"),
                    ("3", "3 Star"),
                    ("4", "4 Star"),
                    ("5", "5 Star"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="accomodations",
            name="remarks",
            field=models.TextField(blank=True),
        ),
    ]
