# Generated by Django 5.2.17 on 2026-10-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accomodations', '0003_accomodations_child_policy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirBNBBooking',
        ),
    ]
