# Generated by Django 4.2.7 on 2026-07-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Accomodations", "0003_accomodations_child_policy_and_more"),
        ("Places", "0009_alter_awesomepackages_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryBuilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("client_name", models.CharField(default="", max_length=50)),
                ("days_spent", models.IntegerField(default=10)),
                ("price", models.IntegerField(default=10)),
                ("description", models.TextField(default="")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from title and client name",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "share_link",
                    models.URLField(
                        blank=True,
                        help_text="Generated link to share the itinerary",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_images",
                    models.ManyToManyField(
                        blank=True, related_name="itineraries", to="Places.destinations"
                    ),
                ),
                (
                    "hotel_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="itineraries",
                        to="Accomodations.accomodationsimage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client_name"], name="SuperMode_i_client__de8367_idx"
                    ),
                    models.Index(fields=["title"], name="SuperMode_i_title_0215af_idx"),
                    models.Index(fields=["slug"], name="SuperMode_i_slug_03c3a6_idx"),
                ],
            },
        ),
    ]
