# Generated by Django 4.2.7 on 2026-07-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SuperMode", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(help_text="Day number for this activity"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Activity title (e.g., 'Departure', 'Game Drive')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the activity"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Location of the activity", max_length=200
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Duration (e.g., '2 hours', 'Full day')",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order within the day"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="SuperMode.itinerarybuilder",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number", "order"],
                "indexes": [
                    models.Index(
                        fields=["itinerary", "day_number"],
                        name="SuperMode_i_itinera_0b4fc4_idx",
                    )
                ],
                "unique_together": {("itinerary", "day_number", "title")},
            },
        ),
    ]
