# Generated by Django 5.2.17 on 2026-10-05 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accomodations', '0004_delete_airbnbbooking'),
        ('ClientRequests', '0001_initial'),
        ('Home', '0017_heroslide_delete_trekkingbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bookings',
            name='airbnb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Accomodations.airbnb'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_type',
            field=models.CharField(choices=[('safari', 'Safari'), ('trekking', 'Trekking'), ('airbnb', 'Airbnb')], db_index=True, default='safari', max_length=10),
        ),
        migrations.AddField(
            model_name='bookings',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='bookings',
            name='trekking_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Home.trekking'),
        ),
    ]
