# Generated by Django 4.2.7 on 2026-05-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trekking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "starRating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        default=5,
                    ),
                ),
                ("days", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("persons", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Kilimanjaro", "kilimanjaro"),
                            ("Kenya", "kenya"),
                            ("Longonot", "longonot"),
                            ("Suswa", "suswa"),
                        ],
                        default="East Africa Tours",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="awesome_packages/default.jpg",
                        upload_to="awesome_packages/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItineraryTreking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "activities",
                    models.TextField(
                        blank=True,
                        help_text="List activities for this day, separated by commas",
                    ),
                ),
                ("accommodation", models.CharField(blank=True, max_length=200)),
                (
                    "meals",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast Only"),
                            ("Half Board", "Breakfast & Dinner"),
                            ("Full Board", "Breakfast, Lunch & Dinner"),
                            ("All Inclusive", "All Meals & Drinks"),
                        ],
                        default="Full Board",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="itinerary_trekking_images/"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_days",
                        to="Home.trekking",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
                "unique_together": {("package", "day_number")},
            },
        ),
    ]
