# Generated by Django 4.2.7 on 2026-05-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_trekking_itinerarytreking"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrekkingBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("number_of_persons", models.IntegerField()),
                ("travel_date", models.DateField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("special_requests", models.TextField(blank=True)),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="Home.trekking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trekking Booking",
                "verbose_name_plural": "Trekking Bookings",
                "ordering": ["-booking_date"],
            },
        ),
    ]
