# Generated by Django 4.2.7 on 2026-05-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Places", "0001_initial"),
        ("Home", "0003_trekkingbooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        help_text="Main advertisement image", upload_to="ads/"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Short description for the ad"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "show_on_pages",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated URLs or leave blank for all pages",
                        max_length=200,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="View Package",
                        help_text="Text for the CTA button",
                        max_length=50,
                    ),
                ),
                (
                    "button_color",
                    models.CharField(
                        default="btn-primary",
                        help_text="Bootstrap button color class",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="Places.awesomepackages",
                    ),
                ),
                (
                    "trekking_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="Home.trekking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "ordering": ["-created_at"],
            },
        ),
    ]
