# Generated by Django 4.2.7 on 2026-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_ad"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="discount_percentage",
            field=models.IntegerField(
                default=0, help_text="Discount percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="show_book_now",
            field=models.BooleanField(default=True, help_text="Show Book Now button"),
        ),
    ]
