# Generated by Django 5.2.7 on 2026-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_destinationscategory_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationscategory',
            name='image_orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=50),
        ),
    ]
