# Generated by Django 4.2.7 on 2026-05-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_ad_discount_percentage_ad_show_book_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trekking",
            name="category",
            field=models.CharField(
                choices=[
                    ("Kilimanjaro", "kilimanjaro"),
                    ("Kenya", "kenya"),
                    ("Longonot", "longonot"),
                    ("Suswa", "suswa"),
                    ("Meru", "meru"),
                ],
                default="East Africa Tours",
                max_length=50,
            ),
        ),
    ]
