# Generated by Django 5.2.7 on 2026-04-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_destinationscategory_image_orientation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='blogcomments',
            old_name='published_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='blogcomments',
            name='blog',
        ),
        migrations.AlterField(
            model_name='awesomepackages',
            name='image',
            field=models.ImageField(default='awesome_packages/default.jpg', upload_to='awesome_packages/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/default.jpg', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, default='testimonials/default.jpg', null=True, upload_to='testimonials/'),
        ),
    ]
