# Generated by Django 5.2.7 on 2026-04-18 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_content_blogcomments_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='categories',
        ),
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.destinations'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='persons',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
