# Generated by Django 4.2.7 on 2026-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0006_alter_trekking_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="descriptions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="blogs",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
