# Generated by Django 4.2.7 on 2026-07-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0007_blogs_descriptions_blogs_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="descriptions",
        ),
    ]
