# Generated by Django 4.2.7 on 2026-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0008_remove_blogs_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="seo_description",
            field=models.TextField(
                blank=True,
                help_text="Keep under 160 characters. Leave blank to auto-generate from content.",
                max_length=160,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogs",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="Keep under 60 characters. Leave blank to auto-generate from title.",
                max_length=60,
                null=True,
            ),
        ),
    ]
