# Generated by Django 4.2.7 on 2026-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0009_blogs_seo_description_blogs_seo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="schema_markup",
            field=models.TextField(
                blank=True, help_text="Paste raw JSON-LD schema here"
            ),
        ),
    ]
