# Generated by Django 4.2.7 on 2026-07-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0010_blogs_schema_markup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
