# Generated by Django 4.2.7 on 2026-07-16 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0014_alter_blogs_content_ckeditor5"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcomments",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Blog Comment",
                "verbose_name_plural": "Blog Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="blogs",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.AlterModelOptions(
            name="brochure",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Brochure",
                "verbose_name_plural": "Brochures",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.AlterModelOptions(
            name="gallerycategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Gallery Category",
                "verbose_name_plural": "Gallery Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="services",
            options={
                "ordering": ["name"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonials",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AlterModelOptions(
            name="trekking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Trekking Package",
                "verbose_name_plural": "Trekking Packages",
            },
        ),
        migrations.RenameField(
            model_name="testimonials",
            old_name="starRating",
            new_name="star_rating",
        ),
        migrations.RenameField(
            model_name="trekking",
            old_name="starRating",
            new_name="star_rating",
        ),
        migrations.AddField(
            model_name="blogcomments",
            name="blog",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_comments",
                to="Home.blogs",
            ),
        ),
        migrations.AddField(
            model_name="testimonials",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trekking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogs",
            name="author",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="title",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="brochure",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to="Home.gallerycategory",
            ),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonials/"),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="trekking",
            name="category",
            field=models.CharField(
                choices=[
                    ("Kilimanjaro", "Kilimanjaro"),
                    ("Kenya", "Kenya"),
                    ("Longonot", "Longonot"),
                    ("Suswa", "Suswa"),
                    ("Meru", "Meru"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="trekking",
            name="location",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="trekking",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="trekking",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="trekkingbooking",
            name="booking_reference",
            field=models.CharField(
                db_index=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="trekkingbooking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trekkingbooking",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="trekkingbooking",
            name="full_name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="trekkingbooking",
            name="travel_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="blogs",
            index=models.Index(fields=["title"], name="Home_blogs_title_793dbc_idx"),
        ),
        migrations.AddIndex(
            model_name="blogs",
            index=models.Index(fields=["slug"], name="Home_blogs_slug_758852_idx"),
        ),
        migrations.AddIndex(
            model_name="blogs",
            index=models.Index(fields=["author"], name="Home_blogs_author_b6df9a_idx"),
        ),
        migrations.AddIndex(
            model_name="blogs",
            index=models.Index(
                fields=["published_date"], name="Home_blogs_publish_00e174_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brochure",
            index=models.Index(fields=["title"], name="Home_brochu_title_e54863_idx"),
        ),
        migrations.AddIndex(
            model_name="brochure",
            index=models.Index(
                fields=["created_at"], name="Home_brochu_created_730a6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gallery",
            index=models.Index(
                fields=["category"], name="Home_galler_categor_3a50d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarytreking",
            index=models.Index(
                fields=["package", "day_number"], name="Home_itiner_package_b7209f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="services",
            index=models.Index(fields=["name"], name="Home_servic_name_5c8c8a_idx"),
        ),
        migrations.AddIndex(
            model_name="testimonials",
            index=models.Index(
                fields=["star_rating"], name="Home_testim_star_ra_82945a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testimonials",
            index=models.Index(
                fields=["created_at"], name="Home_testim_created_a54866_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trekking",
            index=models.Index(fields=["name"], name="Home_trekki_name_db9663_idx"),
        ),
        migrations.AddIndex(
            model_name="trekking",
            index=models.Index(
                fields=["category"], name="Home_trekki_categor_4f8d85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trekking",
            index=models.Index(fields=["price"], name="Home_trekki_price_6b2397_idx"),
        ),
        migrations.AddIndex(
            model_name="trekking",
            index=models.Index(
                fields=["category", "price"], name="Home_trekki_categor_ef7487_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trekkingbooking",
            index=models.Index(
                fields=["booking_reference"], name="Home_trekki_booking_2069d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trekkingbooking",
            index=models.Index(fields=["email"], name="Home_trekki_email_e62503_idx"),
        ),
        migrations.AddIndex(
            model_name="trekkingbooking",
            index=models.Index(
                fields=["booking_status"], name="Home_trekki_booking_38f578_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trekkingbooking",
            index=models.Index(
                fields=["travel_date"], name="Home_trekki_travel__d01226_idx"
            ),
        ),
    ]
