# Generated by Django 5.2.17 on 2026-09-11 19:20

import Home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_blogcomments_options_alter_blogs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(help_text='Main advertisement image', upload_to='ads/', validators=[Home.validators.validate_image_10mb]),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/default.jpg', null=True, upload_to='blog_images/', validators=[Home.validators.validate_image_10mb]),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brochure_images/', validators=[Home.validators.validate_image_10mb]),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='pdf_file',
            field=models.FileField(upload_to='brochures/', validators=[Home.validators.validate_document_20mb]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery_images/', validators=[Home.validators.validate_image_10mb]),
        ),
        migrations.AlterField(
            model_name='itinerarytreking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='itinerary_trekking_images/', validators=[Home.validators.validate_image_10mb]),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[Home.validators.validate_image_10mb]),
        ),
        migrations.AlterField(
            model_name='trekking',
            name='image',
            field=models.ImageField(default='awesome_packages/default.jpg', upload_to='awesome_packages/', validators=[Home.validators.validate_image_10mb]),
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/', validators=[Home.validators.validate_image_10mb])),
                ('caption', models.CharField(blank=True, help_text='Optional alt text / caption', max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Section Image',
                'verbose_name_plural': 'About Section Images',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='Home_abouti_is_acti_566cdf_idx')],
            },
        ),
    ]
