# Generated by Django 5.2.17 on 2026-10-05 19:55

import Home.validators
from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    """HeroSlide's table already exists on databases created before this
    migration was tracked; only create it when it is genuinely absent."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table not in schema_editor.connection.introspection.table_names():
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_ad_image_alter_blogs_image_and_more'),
    ]

    operations = [
        CreateModelIfMissing(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose Image or Video, then upload the matching file below.', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Required when Media type = Image.', null=True, upload_to='hero_slides/images/', validators=[Home.validators.validate_image_10mb])),
                ('video', models.FileField(blank=True, help_text='Required when Media type = Video. MP4 recommended, max 50MB.', null=True, upload_to='hero_slides/videos/', validators=[Home.validators.validate_video_50mb])),
                ('fallback_image', models.ImageField(blank=True, help_text="Shown if the video can't load. Recommended for Video slides.", null=True, upload_to='hero_slides/fallback/', validators=[Home.validators.validate_image_10mb])),
                ('eyebrow_text', models.CharField(blank=True, help_text="Small uppercase line above the title, e.g. 'Explore The World'", max_length=100)),
                ('title', models.CharField(help_text="Main heading, e.g. 'Kenya Safari Tours & East Africa Packages'", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Line under the title, e.g. "Adventure Awaits - Let\'s Go"', max_length=200)),
                ('button_text', models.CharField(blank=True, default='Discover Now', max_length=50)),
                ('button_url', models.CharField(blank=True, default='/about/', help_text='Where the button links to, e.g. /about/ or /packages/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='Home_herosl_is_acti_879c35_idx')],
            },
        ),
        migrations.DeleteModel(
            name='TrekkingBooking',
        ),
    ]
