# Generated by Django 4.2.7 on 2026-07-15 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "email",
                    models.EmailField(default="email@example.com", max_length=254),
                ),
                ("contact", models.CharField(default="", max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("supervisor", "Supervisor"),
                            ("guide", "Safari Guide"),
                            ("driver", "Driver"),
                            ("office", "Office Staff"),
                            ("accountant", "Accountant"),
                            ("marketing", "Marketing"),
                            ("chef", "Chef"),
                            ("housekeeping", "Housekeeping"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        max_length=50,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("management", "Management"),
                            ("operations", "Operations"),
                            ("sales", "Sales & Marketing"),
                            ("accounts", "Accounts"),
                            ("hr", "Human Resources"),
                            ("logistics", "Logistics"),
                        ],
                        default="operations",
                        max_length=50,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("hire_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "emergency_contact",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "emergency_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
