# Generated by Django 4.2.7 on 2026-05-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Day Safari Adventures",
                        max_length=50,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "booking_confirmation_email",
                    models.EmailField(
                        default="info@daysafariadventures.com", max_length=254
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
