# Generated by Django 4.2.7 on 2026-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmailSetup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="company_phone",
            field=models.CharField(default=" +254140919894", max_length=20),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_whatsapp",
            field=models.CharField(default=" +254759379600", max_length=20),
        ),
    ]
