# Generated by Django 4.2.7 on 2026-05-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmailSetup", "0002_companyprofile_company_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="mpesa_payment_link",
            field=models.CharField(
                default="http://192.168.8.179:8001/", max_length=100
            ),
        ),
    ]
