# Generated by Django 4.2.7 on 2026-06-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OurClients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermessage",
            name="user",
        ),
        migrations.DeleteModel(
            name="MessageReply",
        ),
        migrations.DeleteModel(
            name="UserMessage",
        ),
    ]
