# Generated by Django 4.2.7 on 2026-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OurClients", "0003_saveddestination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveddestination",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
