"""
Django settings for DaySafaris project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i9#fnbul=t8lgg$(zv1x^uq0y!+so2rq*&7*p4rph$iai!q&xl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_daraja',
    'Home',
    'OurClients',
    'Places',
    'ClientRequests',
    'Accomodations',
    'Office',
    'Invoices',
    'ChatBot',
    'EmailSetup',
    'FinanceManagement',
    'Payments',
    'MpesaPayment',
    'StripePayment',
    'CryptoTransfer',
    'BankTransfer',
    'SuperMode',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

ROOT_URLCONF = 'DaySafaris.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Home.context_processors.ads_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'DaySafaris.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('sw', _('Swahili')),
    ('fr', _('French')),
    ('de', _('German')),
    ('es', _('Spanish')),
    ('it', _('Italian')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICROOTS = [
    BASE_DIR / 'static',
]

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'

LOGOUT_REDIRECT_URL = 'home'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = ['https://a50c-154-159-252-109.ngrok-free.app', 'https://6457-105-161-237-37.ngrok-free.app']

from decouple import config


# Brevo SMTP Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
EMAIL_FROM_NAME = config('EMAIL_FROM_NAME')
BREVO_API_KEY = config('BREVO_API_KEY')


# SAFARICOM M-PESA API CREDENTIALS
from decouple import config

MPESA_ENVIRONMENT=config("MPESA_ENVIRONMENT")
MPESA_CONSUMER_KEY=config("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET=config("MPESA_CONSUMER_SECRET")
MPESA_SHORTCODE=config("MPESA_SHORTCODE")
MPESA_EXPRESS_SHORTCODE=config("MPESA_EXPRESS_SHORTCODE")
MPESA_SHORTCODE_TYPE=config("MPESA_SHORTCODE_TYPE")
MPESA_PASSKEY=config("MPESA_PASSKEY")
MPESA_INITIATOR_USERNAME=config("MPESA_INITIATOR_USERNAME")
MPESA_INITIATOR_SECURITY_CREDENTIAL=config("MPESA_INITIATOR_SECURITY_CREDENTIAL")


